version: "3"
services:
    cocolog-nginx:
        container_name: "cocolog-nginx"
        build:
            context: ./docker/nginx
        depends_on:
            - cocolog-app
        ports:
            - 80:80
        volumes:
            - ./:/src

    cocolog-app:
        container_name: "cocolog-app"
        build:
            context: ./docker/php
        depends_on:
            - cocolog-mysql
        ports:
            - 5173:5173
        volumes:
            - ./:/src
            - /src/node_modules
            - /src/vendor
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    cocolog-mysql:
        image: mysql:8.0.33
        command: --max_allowed_packet=32505856
        container_name: "cocolog-mysql"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            - MYSQL_USERNAME=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - PMA_HOST=cocolog-mysql

    cocolog-redis:
        image: redis:alpine
        container_name: "cocolog-redis"
        ports:
            - 16379:6379
